service: serverless
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  profile: training
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource:
        - "*"

functions:
  queue-handler:
    handler: handler.handler
    name: queueHandler-${self:provider.stage}
    memorySize: 128
    timeout: 15
    events:
      - http:
          path: queue-handler
          method: post
          cors: true
  queue-consumer:
    handler: consumer.handler
    name: consumer-${self:provider.stage}
    memorySize: 256